- name: Configure neo4j.conf
  template:
    src: neo4j.conf.j2
    dest: /etc/neo4j/neo4j.conf
    mode: '0644'
  notify: Restart Neo4j

- name: Set password for default user
  shell: echo -e "neo4j\n{{ neo4j_password }}\n{{ neo4j_password }}" | cypher-shell -u neo4j -p neo4j || true
  environment:
    NEO4J_AUTH: neo4j/neo4j
  args:
    executable: /bin/bash
