- name: Configure neo4j.conf
  template:
    src: neo4j.conf.j2
    dest: /etc/neo4j/neo4j.conf
    mode: '0644'
  notify: Restart Neo4j

- name: Wait for Neo4j to be fully operational
  wait_for:
    port: 7687
    timeout: 30

- name: Change Neo4j default password
  shell: |
    echo 'ALTER CURRENT USER SET PASSWORD FROM "neo4j" TO "{{ neo4j_password }}";' | cypher-shell -u neo4j -p neo4j --format plain --database system
  environment:
    NEO4J_AUTH: neo4j/neo4j
  args:
    executable: /bin/bash
