- name: Configure neo4j.conf
  template:
    src: neo4j.conf.j2
    dest: /etc/neo4j/neo4j.conf
    mode: '0644'
  notify: Restart Neo4j

- name: Change neo4j default password
  shell: |
    cypher-shell -u neo4j -p neo4j "ALTER CURRENT USER SET PASSWORD FROM 'neo4j' TO '{{ neo4j_password }}';"
  environment:
    NEO4J_AUTH: neo4j/neo4j
  args:
    executable: /bin/bash
  ignore_errors: yes  # If password is already changed, this avoids failure

