- name: Install dependencies
  apt:
    name:
      - curl
      - wget
      - unzip
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - lsb-release
    state: present
    update_cache: yes

- name: Add Adoptium GPG key
  ansible.builtin.apt_key:
    url: https://packages.adoptium.net/artifactory/api/gpg/key/public
    state: present

- name: Add Adoptium APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.adoptium.net/artifactory/deb bookworm main"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java 21 JDK
  ansible.builtin.apt:
    name: temurin-21-jdk
    state: present

- name: Add Neo4j GPG key
  shell: |
    curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key | gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
  args:
    creates: /usr/share/keyrings/neo4j.gpg

- name: Add Neo4j APT repository
  copy:
    dest: /etc/apt/sources.list.d/neo4j.list
    content: |
      deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable latest

- name: Update apt cache after adding Neo4j repo
  apt:
    update_cache: yes

- name: Install Neo4j
  apt:
    name: neo4j
    state: present

- name: Enable and start Neo4j service
  systemd:
    name: neo4j
    enabled: yes
    state: started

- include_tasks: configure.yml
